import { useEffect, useState } from 'react'
import { supabase } from '../../data/supabase'
import { Modal } from '../../components/Modal'

type Usuario={usuario_id:string;email:string;nombre:string;habilitado:boolean;roles?:string[]};type Rol={id:string;nombre:string};type Asignacion={asignacion_id:string;rol_nombre:string}
export function Usuarios(){
 const [usuarios,setUsuarios]=useState<Usuario[]>([]),[roles,setRoles]=useState<Rol[]>([]),[asignaciones,setAsignaciones]=useState<Record<string,Asignacion[]>>({}),[rol,setRol]=useState(''),[filtro,setFiltro]=useState(''),[filtroRol,setFiltroRol]=useState(''),[modal,setModal]=useState<{title:string;message:string;tone:'success'|'error'|'confirm';confirm?:()=>void}|null>(null)
 const cargar=async()=>{const[u,r]=await Promise.all([supabase.rpc('listar_usuarios_google'),supabase.from('roles').select('id,nombre').eq('activo',true).order('nombre')]);if(u.error||r.error)setModal({title:'Error',message:'No se pudieron cargar usuarios y roles.',tone:'error'});else{setUsuarios((u.data??[]) as Usuario[]);setRoles((r.data??[]) as Rol[]);if(!rol&&r.data?.[0])setRol(r.data[0].id)}};useEffect(()=>{void cargar()},[])
 const ver=async(u:Usuario)=>{const{data,error}=await supabase.rpc('listar_asignaciones_usuario',{p_usuario:u.usuario_id});if(error)setModal({title:'Error',message:'No se pudieron cargar las asignaciones.',tone:'error'});else setAsignaciones(p=>({...p,[u.usuario_id]:(data??[]) as Asignacion[]}))}
 const revocar=(u:Usuario,a:Asignacion)=>setModal({title:'Revocar rol',message:`¿Querés revocar ${a.rol_nombre} a ${u.email}?`,tone:'confirm',confirm:async()=>{setModal(null);const{error}=await supabase.rpc('revocar_rol',{p_asignacion:a.asignacion_id});if(error)setModal({title:'Error',message:'No se pudo revocar el rol.',tone:'error'});else{await ver(u);await cargar();setModal({title:'Rol revocado',message:`Se revocó ${a.rol_nombre} a ${u.email}.`,tone:'success'})}}})
 const asignar=async(u:Usuario)=>{const{error}=await supabase.rpc('asignar_rol',{p_usuario:u.usuario_id,p_rol:rol,p_deporte:null as unknown as string,p_plantel:null as unknown as string});if(error)setModal({title:'Error',message:'No se pudo asignar el rol.',tone:'error'});else{await ver(u);setModal({title:'Rol asignado',message:`Se asignó ${roles.find(r=>r.id===rol)?.nombre??'el rol'} a ${u.email}.`,tone:'success'})}}
 const habilitar=async(u:Usuario)=>{const{error}=await supabase.rpc('habilitar_usuario',{p_usuario:u.usuario_id,p_nombre:u.nombre||u.email,p_activo:true});if(error)setModal({title:'Error',message:'No se pudo habilitar el usuario.',tone:'error'});else{await cargar();setModal({title:'Usuario habilitado',message:`${u.email} ya puede ingresar.`,tone:'success'})}}
 const visibles=usuarios.filter(u=>`${u.nombre} ${u.email}`.toLowerCase().includes(filtro.toLowerCase())&&(!filtroRol||(u.roles??[]).includes(filtroRol)))
 return <><section className="panel"><h2>Usuarios y roles</h2><p className="hint">Sólo el administrador principal puede habilitar identidades Google y asignar perfiles.</p><div className="filters"><label>Buscar<input value={filtro} placeholder="Nombre o email" onChange={e=>setFiltro(e.target.value)}/></label><label>Filtrar por rol<select value={filtroRol} onChange={e=>setFiltroRol(e.target.value)}><option value="">Todos</option>{roles.map(r=><option key={r.id} value={r.nombre}>{r.nombre}</option>)}</select></label></div><label>Rol a asignar<select value={rol} onChange={e=>setRol(e.target.value)}>{roles.map(r=><option key={r.id} value={r.id}>{r.nombre}</option>)}</select></label><ul className="catalogo">{visibles.map(u=><li key={u.usuario_id}><span><strong>{u.nombre||u.email}</strong><br/><small>{u.email}</small><br/><small>Rol: {(u.roles??[]).join(', ')||'Sin rol'}</small>{(asignaciones[u.usuario_id]??[]).map(a=><span className="role-row" key={a.asignacion_id}><br/><small>{a.rol_nombre}</small><button className="secondary small" onClick={()=>revocar(u,a)}>Revocar</button></span>)}</span><span>{!u.habilitado?<button className="small" onClick={()=>void habilitar(u)}>Habilitar</button>:<><button className="small" onClick={()=>void asignar(u)}>Asignar rol</button><button className="secondary small" onClick={()=>void ver(u)}>Ver roles</button></>}</span></li>)}</ul></section><Modal open={!!modal} title={modal?.title??''} message={modal?.message??''} tone={modal?.tone} onClose={()=>setModal(null)} onConfirm={modal?.confirm}/></>
}
