import { useEffect, useState } from 'react'
import { supabase } from '../../data/supabase'

type Plantel = { id: string; equipos: { nombre: string } | null; deportes: { nombre: string } | null; categorias: { nombre: string } | null; temporadas: { nombre: string } | null }
type Fila = { jugador_id: string; nombre: string; apellido: string; entrenamientos_realizados: number; presentes: number; ausentes: number; porcentaje: number | null }

export function DashboardAsistencia() {
  const [planteles, setPlanteles] = useState<Plantel[]>([]), [plantel, setPlantel] = useState(''), [deporte, setDeporte] = useState(''), [categoria, setCategoria] = useState(''), [temporada, setTemporada] = useState(''), [filas, setFilas] = useState<Fila[]>([]), [cargando, setCargando] = useState(false), [mensaje, setMensaje] = useState<string | null>(null)
  useEffect(() => { void supabase.from('planteles').select('id,equipos(nombre),deportes(nombre),categorias(nombre),temporadas(nombre)').eq('activo', true).order('id').then(({ data, error }) => { if (error) setMensaje('No se pudieron cargar los planteles.'); else setPlanteles((data ?? []) as Plantel[]) }) }, [])
  const cargar = async (id: string) => { setPlantel(id); setMensaje(null); if (!id) { setFilas([]); return }; setCargando(true); const { data, error } = await supabase.rpc('reporte_asistencia_plantel', { p_plantel_id: id }); setCargando(false); if (error) setMensaje(`No se pudo cargar la asistencia: ${error.message}`); else setFilas((data ?? []) as Fila[]) }
  const filtrados = planteles.filter(p => (!deporte || p.deportes?.nombre === deporte) && (!categoria || p.categorias?.nombre === categoria) && (!temporada || p.temporadas?.nombre === temporada)); const opciones = (campo: 'deportes' | 'categorias' | 'temporadas') => [...new Set(planteles.map(p => p[campo]?.nombre).filter(Boolean))] as string[]
  const sinEntrenamientos = filas.length > 0 && filas.every(f => f.entrenamientos_realizados === 0)
  return <section className="panel"><h2>Dashboard de asistencia</h2><p className="hint">Resumen por jugador del plantel seleccionado.</p><div className="filters"><label>Deporte<select value={deporte} onChange={e => { setDeporte(e.target.value); setPlantel(''); setFilas([]) }}><option value="">Todos</option>{opciones('deportes').map(x => <option key={x}>{x}</option>)}</select></label><label>Categoría<select value={categoria} onChange={e => { setCategoria(e.target.value); setPlantel(''); setFilas([]) }}><option value="">Todas</option>{opciones('categorias').map(x => <option key={x}>{x}</option>)}</select></label><label>Temporada<select value={temporada} onChange={e => { setTemporada(e.target.value); setPlantel(''); setFilas([]) }}><option value="">Todas</option>{opciones('temporadas').map(x => <option key={x}>{x}</option>)}</select></label></div><label>Plantel<select value={plantel} onChange={e => void cargar(e.target.value)}><option value="">Seleccionar</option>{filtrados.map(p => <option key={p.id} value={p.id}>{p.equipos?.nombre} · {p.deportes?.nombre} · {p.categorias?.nombre} · {p.temporadas?.nombre}</option>)}</select></label>{cargando && <p className="hint">Cargando asistencia…</p>}{plantel && !cargando && filas.length === 0 && <p className="hint">No hay jugadores o entrenamientos registrados para este plantel.</p>}{plantel && !cargando && sinEntrenamientos && <p className="hint">Hay jugadores, pero todavía no hay entrenamientos realizados.</p>}{filas.length > 0 && !sinEntrenamientos && <div className="table-wrap"><table><thead><tr><th>Jugador</th><th>Entrenamientos</th><th>Presentes</th><th>Ausentes</th><th>Asistencia</th></tr></thead><tbody>{filas.map(f => <tr key={f.jugador_id}><td>{f.apellido}, {f.nombre}</td><td>{f.entrenamientos_realizados}</td><td>{f.presentes}</td><td>{f.ausentes}</td><td>{f.porcentaje === null ? 'Sin datos' : `${f.porcentaje}%`}</td></tr>)}</tbody></table></div>}{mensaje && <p className="error">{mensaje}</p>}</section>
}
