import { useEffect, useState } from 'react'
import { useContextoDeportivo } from '../../app/ContextoDeportivo'
import { supabase } from '../../data/supabase'

type Plantel = { id: string; equipos: { nombre: string } | null; deportes: { nombre: string } | null; categorias: { nombre: string } | null; temporadas: { nombre: string } | null }
type Fila = { jugador_id: string; nombre: string; apellido: string; entrenamientos_realizados: number; presentes: number; ausentes: number; porcentaje: number | null }

export function DashboardAsistencia() {
  const { deporte, categoria, temporada } = useContextoDeportivo()
  const [planteles, setPlanteles] = useState<Plantel[]>([]), [plantel, setPlantel] = useState(''), [filas, setFilas] = useState<Fila[]>([]), [cargando, setCargando] = useState(false), [mensaje, setMensaje] = useState<string | null>(null)
  useEffect(() => { let activo = true; const cargar = async () => { setPlantel(''); setFilas([]); setMensaje(null); let query = supabase.from('planteles').select('id,equipos(nombre),deportes(nombre),categorias(nombre),temporadas(nombre)').eq('activo', true).order('id'); if (deporte) query = query.eq('deporte_id', deporte); if (categoria) query = query.eq('categoria_id', categoria); if (temporada) query = query.eq('temporada_id', temporada); const { data, error } = await query; if (!activo) return; if (error) setMensaje('No se pudieron cargar los planteles.'); else setPlanteles((data ?? []) as Plantel[]) }; void cargar(); return () => { activo = false } }, [deporte, categoria, temporada])
  const cargar = async (id: string) => { setPlantel(id); setMensaje(null); if (!id) { setFilas([]); return }; setCargando(true); const { data, error } = await supabase.rpc('reporte_asistencia_plantel', { p_plantel_id: id }); setCargando(false); if (error) setMensaje('No se pudo cargar la asistencia.'); else setFilas((data ?? []) as Fila[]) }
  const sinEntrenamientos = filas.length > 0 && filas.every(f => f.entrenamientos_realizados === 0)
  return <section className="panel report-panel"><div className="panel-heading"><p className="eyebrow">Reporte</p><h2>Asistencia</h2><p className="hint">El contexto global filtra los planteles disponibles.</p></div><label>Plantel<select value={plantel} onChange={e => void cargar(e.target.value)}><option value="">Seleccionar</option>{planteles.map(p => <option key={p.id} value={p.id}>{p.equipos?.nombre} · {p.deportes?.nombre} · {p.categorias?.nombre} · {p.temporadas?.nombre}</option>)}</select></label>{cargando && <p className="hint">Cargando asistencia…</p>}{!cargando && !planteles.length && <p className="empty-state">No hay planteles para el contexto seleccionado.</p>}{plantel && !cargando && filas.length === 0 && <p className="empty-state">No hay jugadores o entrenamientos registrados para este plantel.</p>}{plantel && !cargando && sinEntrenamientos && <p className="empty-state">Hay jugadores, pero todavía no hay entrenamientos realizados.</p>}{filas.length > 0 && !sinEntrenamientos && <div className="table-wrap"><table><thead><tr><th>Jugador</th><th>Entrenamientos</th><th>Presentes</th><th>Ausentes</th><th>Asistencia</th></tr></thead><tbody>{filas.map(f => <tr key={f.jugador_id}><td>{f.apellido}, {f.nombre}</td><td>{f.entrenamientos_realizados}</td><td>{f.presentes}</td><td>{f.ausentes}</td><td>{f.porcentaje === null ? 'Sin datos' : `${f.porcentaje}%`}</td></tr>)}</tbody></table></div>}{mensaje && <p className="error">{mensaje}</p>}</section>
}
