CREATE TABLE "ROLES"(
    "ID_ROL" INT NOT NULL,
    "NOMBRE" VARCHAR(50) NOT NULL,
    "AMBITO" NVARCHAR(255) CHECK
        ("AMBITO" IN(N'Global', N'Deporte')) NOT NULL DEFAULT 'Global'
);
ALTER TABLE
    "ROLES" ADD CONSTRAINT "roles_id_rol_primary" PRIMARY KEY("ID_ROL");
CREATE UNIQUE INDEX "roles_nombre_unique" ON
    "ROLES"("NOMBRE");
CREATE TABLE "DEPORTES"(
    "ID_DEPORTE" INT NOT NULL,
    "NOMBRE" VARCHAR(50) NOT NULL,
    "DESCRIPCION" VARCHAR(200) NULL,
    "ACTIVO" BIT NOT NULL DEFAULT 1
);
ALTER TABLE
    "DEPORTES" ADD CONSTRAINT "deportes_id_deporte_primary" PRIMARY KEY("ID_DEPORTE");
CREATE UNIQUE INDEX "deportes_nombre_unique" ON
    "DEPORTES"("NOMBRE");
CREATE TABLE "CATEGORIAS"(
    "ID_CATEGORIA" INT NOT NULL,
    "NOMBRE" VARCHAR(50) NOT NULL
);
ALTER TABLE
    "CATEGORIAS" ADD CONSTRAINT "categorias_id_categoria_primary" PRIMARY KEY("ID_CATEGORIA");
CREATE UNIQUE INDEX "categorias_nombre_unique" ON
    "CATEGORIAS"("NOMBRE");
CREATE TABLE "EQUIPOS"(
    "ID_EQUIPO" INT NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "CONTACTO" VARCHAR(100) NULL,
    "TELEFONO" VARCHAR(50) NULL,
    "EMAIL" VARCHAR(150) NULL,
    "ES_PROPIO" BIT NOT NULL
);
ALTER TABLE
    "EQUIPOS" ADD CONSTRAINT "equipos_id_equipo_primary" PRIMARY KEY("ID_EQUIPO");
CREATE TABLE "SEDES"(
    "ID_SEDE" INT NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "DIRECCION" VARCHAR(200) NULL
);
ALTER TABLE
    "SEDES" ADD CONSTRAINT "sedes_id_sede_primary" PRIMARY KEY("ID_SEDE");
CREATE TABLE "USUARIOS"(
    "ID_USUARIO" INT NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "APELLIDO" VARCHAR(100) NOT NULL,
    "EMAIL" VARCHAR(150) NOT NULL,
    "PASSWORD_HASH" VARCHAR(255) NOT NULL,
    "SALT" VARCHAR(255) NOT NULL,
    "DNI" VARCHAR(20) NOT NULL,
    "FECHA_NACIMIENTO" DATE NOT NULL,
    "TELEFONO" VARCHAR(50) NULL,
    "EMAIL_PADRE" VARCHAR(150) NULL,
    "NOMBRE_PADRE" VARCHAR(150) NULL,
    "TOKEN_ACTIVACION" VARCHAR(20) NULL,
    "TOKEN_EXPIRA" DATETIME NULL,
    "ID_ROL_GLOBAL" INT NOT NULL,
    "ACTIVADO" BIT NOT NULL,
    "CONFIRMADO" BIT NOT NULL,
    "FECHA_REGISTRO" DATETIME NOT NULL DEFAULT GETDATE());
ALTER TABLE
    "USUARIOS" ADD CONSTRAINT "usuarios_id_usuario_primary" PRIMARY KEY("ID_USUARIO");
CREATE UNIQUE INDEX "usuarios_email_unique" ON
    "USUARIOS"("EMAIL");
CREATE UNIQUE INDEX "usuarios_dni_unique" ON
    "USUARIOS"("DNI");
CREATE TABLE "USUARIO_DEPORTE"(
    "ID_USUDEP" INT NOT NULL,
    "ID_USUARIO" INT NOT NULL,
    "ID_DEPORTE" INT NOT NULL,
    "ID_CATEGORIA" INT NULL,
    "ID_ROL" INT NOT NULL,
    "ID_SEDE" INT NULL,
    "NUMERO_CAMISETA" INT NULL,
    "F_INICIO" DATE NOT NULL DEFAULT GETDATE(), "ACTIVO" BIT NOT NULL DEFAULT 1);
CREATE INDEX "usuario_deporte_id_deporte_id_categoria_index" ON
    "USUARIO_DEPORTE"("ID_DEPORTE", "ID_CATEGORIA");
CREATE UNIQUE INDEX "ID_USUARIO_ID_DEPORTE_ID_CATEGORIA_ID_ROL_unique" ON
    "USUARIO_DEPORTE"(
        "ID_USUARIO",
        "ID_DEPORTE",
        "ID_CATEGORIA",
        "ID_ROL"
    );
ALTER TABLE
    "USUARIO_DEPORTE" ADD CONSTRAINT "usuario_deporte_id_usudep_primary" PRIMARY KEY("ID_USUDEP");
CREATE INDEX "usuario_deporte_id_usuario_index" ON
    "USUARIO_DEPORTE"("ID_USUARIO");
CREATE TABLE "TORNEOS"(
    "ID_TORNEO" INT NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "ID_DEPORTE" INT NOT NULL,
    "ID_CATEGORIA" INT NOT NULL,
    "ANIO" INT NOT NULL,
    "ACTIVO" BIT NOT NULL DEFAULT 1
);
ALTER TABLE
    "TORNEOS" ADD CONSTRAINT "torneos_id_torneo_primary" PRIMARY KEY("ID_TORNEO");
CREATE TABLE "FECHAS"(
    "ID_FECHA" INT NOT NULL,
    "ID_TORNEO" INT NOT NULL,
    "NRO_FECHA" INT NOT NULL,
    "FECHA" DATE NOT NULL
);
CREATE UNIQUE INDEX "fechas_id_torneo_nro_fecha_unique" ON
    "FECHAS"("ID_TORNEO", "NRO_FECHA");
ALTER TABLE
    "FECHAS" ADD CONSTRAINT "fechas_id_fecha_primary" PRIMARY KEY("ID_FECHA");
CREATE TABLE "PARTIDOS"(
    "ID_PARTIDO" INT NOT NULL,
    "ID_FECHA" INT NOT NULL,
    "ID_EQUIPO_LOCAL" INT NOT NULL,
    "ID_EQUIPO_VISITANTE" INT NOT NULL,
    "ID_SEDE" INT NULL,
    "FECHA_HORA" DATETIME NOT NULL,
    "ESTADO" VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
    "JUGADOR_DESTACADO_ID" INT NULL,
    "OBSERVACIONES" VARCHAR(MAX) NULL
);
CREATE INDEX "partidos_estado_fecha_hora_index" ON
    "PARTIDOS"("ESTADO", "FECHA_HORA");
ALTER TABLE
    "PARTIDOS" ADD CONSTRAINT "partidos_id_partido_primary" PRIMARY KEY("ID_PARTIDO");
CREATE INDEX "partidos_id_fecha_index" ON
    "PARTIDOS"("ID_FECHA");
CREATE TABLE "RESULTADOS"(
    "ID_RESULTADO" INT NOT NULL,
    "ID_PARTIDO" INT NOT NULL,
    "GOLES_LOCAL" INT NOT NULL,
    "GOLES_VISITANTE" INT NOT NULL
);
ALTER TABLE
    "RESULTADOS" ADD CONSTRAINT "resultados_id_resultado_primary" PRIMARY KEY("ID_RESULTADO");
CREATE UNIQUE INDEX "resultados_id_partido_unique" ON
    "RESULTADOS"("ID_PARTIDO");
CREATE TABLE "CONVOCATORIAS"(
    "ID_CONVOCATORIA" INT NOT NULL,
    "ID_PARTIDO" INT NOT NULL,
    "ID_USUARIO" INT NOT NULL,
    "ESTADO" VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
    "ASISTIO" BIT NOT NULL,
    "METODO_TRANSPORTE" VARCHAR(50) NULL,
    "AUTORIZACION_FIRMADA" BIT NOT NULL,
    "FECHA_RESPUESTA" DATETIME NULL
);
CREATE UNIQUE INDEX "convocatorias_id_partido_id_usuario_unique" ON
    "CONVOCATORIAS"("ID_PARTIDO", "ID_USUARIO");
ALTER TABLE
    "CONVOCATORIAS" ADD CONSTRAINT "convocatorias_id_convocatoria_primary" PRIMARY KEY("ID_CONVOCATORIA");
CREATE INDEX "convocatorias_id_partido_index" ON
    "CONVOCATORIAS"("ID_PARTIDO");
CREATE INDEX "convocatorias_id_usuario_index" ON
    "CONVOCATORIAS"("ID_USUARIO");
CREATE TABLE "AUTORIZACIONES"(
    "ID_AUTORIZACION" INT NOT NULL,
    "ID_CONVOCATORIA" INT NOT NULL,
    "FIRMA_DIGITAL" VARCHAR(255) NULL,
    "IP_FIRMA" VARCHAR(50) NULL,
    "FECHA_FIRMA" DATETIME NULL,
    "DOCUMENTO_URL" VARCHAR(500) NULL
);
ALTER TABLE
    "AUTORIZACIONES" ADD CONSTRAINT "autorizaciones_id_autorizacion_primary" PRIMARY KEY("ID_AUTORIZACION");
CREATE UNIQUE INDEX "autorizaciones_id_convocatoria_unique" ON
    "AUTORIZACIONES"("ID_CONVOCATORIA");
CREATE TABLE "TITULARES"(
    "ID_TITULAR" INT NOT NULL,
    "ID_PARTIDO" INT NOT NULL,
    "ID_USUARIO" INT NOT NULL,
    "NUMERO_CAMISETA" INT NOT NULL,
    "ES_CAPITAN" BIT NOT NULL
);
CREATE UNIQUE INDEX "titulares_id_partido_id_usuario_unique" ON
    "TITULARES"("ID_PARTIDO", "ID_USUARIO");
ALTER TABLE
    "TITULARES" ADD CONSTRAINT "titulares_id_titular_primary" PRIMARY KEY("ID_TITULAR");
CREATE TABLE "CAMBIOS"(
    "ID_CAMBIO" INT NOT NULL,
    "ID_PARTIDO" INT NOT NULL,
    "ID_USUARIO_SALE" INT NOT NULL,
    "ID_USUARIO_ENTRA" INT NOT NULL,
    "MINUTO" INT NOT NULL,
    "MOTIVO" VARCHAR(100) NULL
);
ALTER TABLE
    "CAMBIOS" ADD CONSTRAINT "cambios_id_cambio_primary" PRIMARY KEY("ID_CAMBIO");
CREATE TABLE "TIPOS_ESTADISTICA"(
    "ID_TIPO_EST" INT NOT NULL,
    "NOMBRE" VARCHAR(50) NOT NULL
);
ALTER TABLE
    "TIPOS_ESTADISTICA" ADD CONSTRAINT "tipos_estadistica_id_tipo_est_primary" PRIMARY KEY("ID_TIPO_EST");
CREATE UNIQUE INDEX "tipos_estadistica_nombre_unique" ON
    "TIPOS_ESTADISTICA"("NOMBRE");
CREATE TABLE "ESTADISTICAS"(
    "ID_ESTADISTICA" INT NOT NULL,
    "ID_PARTIDO" INT NOT NULL,
    "ID_USUARIO" INT NOT NULL,
    "ID_TIPO_EST" INT NOT NULL,
    "MINUTO" INT NOT NULL,
    "ID_USUARIO_ASISTENCIA" INT NULL
);
ALTER TABLE
    "ESTADISTICAS" ADD CONSTRAINT "estadisticas_id_estadistica_primary" PRIMARY KEY("ID_ESTADISTICA");
CREATE INDEX "estadisticas_id_partido_index" ON
    "ESTADISTICAS"("ID_PARTIDO");
CREATE INDEX "estadisticas_id_usuario_index" ON
    "ESTADISTICAS"("ID_USUARIO");
CREATE TABLE "TIPOS_SANCION"(
    "ID_TIPO_SANC" INT NOT NULL,
    "NOMBRE" VARCHAR(50) NOT NULL,
    "PARTIDOS_SUSPENSION" INT NOT NULL
);
ALTER TABLE
    "TIPOS_SANCION" ADD CONSTRAINT "tipos_sancion_id_tipo_sanc_primary" PRIMARY KEY("ID_TIPO_SANC");
CREATE UNIQUE INDEX "tipos_sancion_nombre_unique" ON
    "TIPOS_SANCION"("NOMBRE");
CREATE TABLE "SANCIONES"(
    "ID_SANCION" INT NOT NULL,
    "ID_PARTIDO" INT NOT NULL,
    "ID_USUARIO" INT NOT NULL,
    "ID_TIPO_SANC" INT NOT NULL,
    "MINUTO" INT NOT NULL,
    "MOTIVO" VARCHAR(255) NULL
);
ALTER TABLE
    "SANCIONES" ADD CONSTRAINT "sanciones_id_sancion_primary" PRIMARY KEY("ID_SANCION");
CREATE INDEX "sanciones_id_partido_index" ON
    "SANCIONES"("ID_PARTIDO");
ALTER TABLE
    "SANCIONES" ADD CONSTRAINT "sanciones_id_partido_foreign" FOREIGN KEY("ID_PARTIDO") REFERENCES "PARTIDOS"("ID_PARTIDO");
ALTER TABLE
    "USUARIO_DEPORTE" ADD CONSTRAINT "usuario_deporte_id_usuario_foreign" FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "ESTADISTICAS" ADD CONSTRAINT "estadisticas_id_usuario_asistencia_foreign" FOREIGN KEY("ID_USUARIO_ASISTENCIA") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "ESTADISTICAS" ADD CONSTRAINT "estadisticas_id_partido_foreign" FOREIGN KEY("ID_PARTIDO") REFERENCES "PARTIDOS"("ID_PARTIDO");
ALTER TABLE
    "PARTIDOS" ADD CONSTRAINT "partidos_id_sede_foreign" FOREIGN KEY("ID_SEDE") REFERENCES "SEDES"("ID_SEDE");
ALTER TABLE
    "CAMBIOS" ADD CONSTRAINT "cambios_id_partido_foreign" FOREIGN KEY("ID_PARTIDO") REFERENCES "PARTIDOS"("ID_PARTIDO");
ALTER TABLE
    "TITULARES" ADD CONSTRAINT "titulares_id_usuario_foreign" FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "SANCIONES" ADD CONSTRAINT "sanciones_id_usuario_foreign" FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "USUARIOS" ADD CONSTRAINT "usuarios_id_rol_global_foreign" FOREIGN KEY("ID_ROL_GLOBAL") REFERENCES "ROLES"("ID_ROL");
ALTER TABLE
    "PARTIDOS" ADD CONSTRAINT "partidos_id_equipo_local_foreign" FOREIGN KEY("ID_EQUIPO_LOCAL") REFERENCES "EQUIPOS"("ID_EQUIPO");
ALTER TABLE
    "PARTIDOS" ADD CONSTRAINT "partidos_id_equipo_visitante_foreign" FOREIGN KEY("ID_EQUIPO_VISITANTE") REFERENCES "EQUIPOS"("ID_EQUIPO");
ALTER TABLE
    "TORNEOS" ADD CONSTRAINT "torneos_id_deporte_foreign" FOREIGN KEY("ID_DEPORTE") REFERENCES "DEPORTES"("ID_DEPORTE");
ALTER TABLE
    "TITULARES" ADD CONSTRAINT "titulares_id_partido_foreign" FOREIGN KEY("ID_PARTIDO") REFERENCES "PARTIDOS"("ID_PARTIDO");
ALTER TABLE
    "USUARIO_DEPORTE" ADD CONSTRAINT "usuario_deporte_id_sede_foreign" FOREIGN KEY("ID_SEDE") REFERENCES "SEDES"("ID_SEDE");
ALTER TABLE
    "PARTIDOS" ADD CONSTRAINT "partidos_id_partido_foreign" FOREIGN KEY("ID_PARTIDO") REFERENCES "RESULTADOS"("ID_PARTIDO");
ALTER TABLE
    "ESTADISTICAS" ADD CONSTRAINT "estadisticas_id_usuario_foreign" FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "CAMBIOS" ADD CONSTRAINT "cambios_id_usuario_entra_foreign" FOREIGN KEY("ID_USUARIO_ENTRA") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "PARTIDOS" ADD CONSTRAINT "partidos_id_fecha_foreign" FOREIGN KEY("ID_FECHA") REFERENCES "FECHAS"("ID_FECHA");
ALTER TABLE
    "CONVOCATORIAS" ADD CONSTRAINT "convocatorias_id_usuario_foreign" FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "PARTIDOS" ADD CONSTRAINT "partidos_jugador_destacado_id_foreign" FOREIGN KEY("JUGADOR_DESTACADO_ID") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "CONVOCATORIAS" ADD CONSTRAINT "convocatorias_id_convocatoria_foreign" FOREIGN KEY("ID_CONVOCATORIA") REFERENCES "AUTORIZACIONES"("ID_CONVOCATORIA");
ALTER TABLE
    "FECHAS" ADD CONSTRAINT "fechas_id_torneo_foreign" FOREIGN KEY("ID_TORNEO") REFERENCES "TORNEOS"("ID_TORNEO");
ALTER TABLE
    "USUARIO_DEPORTE" ADD CONSTRAINT "usuario_deporte_id_deporte_foreign" FOREIGN KEY("ID_DEPORTE") REFERENCES "DEPORTES"("ID_DEPORTE");
ALTER TABLE
    "CONVOCATORIAS" ADD CONSTRAINT "convocatorias_id_partido_foreign" FOREIGN KEY("ID_PARTIDO") REFERENCES "PARTIDOS"("ID_PARTIDO");
ALTER TABLE
    "ESTADISTICAS" ADD CONSTRAINT "estadisticas_id_tipo_est_foreign" FOREIGN KEY("ID_TIPO_EST") REFERENCES "TIPOS_ESTADISTICA"("ID_TIPO_EST");
ALTER TABLE
    "SANCIONES" ADD CONSTRAINT "sanciones_id_tipo_sanc_foreign" FOREIGN KEY("ID_TIPO_SANC") REFERENCES "TIPOS_SANCION"("ID_TIPO_SANC");
ALTER TABLE
    "USUARIO_DEPORTE" ADD CONSTRAINT "usuario_deporte_id_rol_foreign" FOREIGN KEY("ID_ROL") REFERENCES "ROLES"("ID_ROL");
ALTER TABLE
    "TORNEOS" ADD CONSTRAINT "torneos_id_categoria_foreign" FOREIGN KEY("ID_CATEGORIA") REFERENCES "CATEGORIAS"("ID_CATEGORIA");
ALTER TABLE
    "CAMBIOS" ADD CONSTRAINT "cambios_id_usuario_sale_foreign" FOREIGN KEY("ID_USUARIO_SALE") REFERENCES "USUARIOS"("ID_USUARIO");
ALTER TABLE
    "USUARIO_DEPORTE" ADD CONSTRAINT "usuario_deporte_id_categoria_foreign" FOREIGN KEY("ID_CATEGORIA") REFERENCES "CATEGORIAS"("ID_CATEGORIA");