import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../../data/supabase'

type Plantel = { id: string; nombre: string }
type Inscripcion = { id: string; jugador_id: string; jugadores: { nombre: string; apellido: string } | null; camiseta: number | null }
type Entrenamiento = { id: string; plantel_id: string; inicio: string; estado: string }

export function Asistencia() {
  const [planteles,setPlanteles]=useState<Plantel[]>([]),[plantel,setPlantel]=useState(''),[entrenamientos,setEntrenamientos]=useState<Entrenamiento[]>([]),[entrenamiento,setEntrenamiento]=useState(''),[inscripciones,setInscripciones]=useState<Inscripcion[]>([]),[estados,setEstados]=useState<Record<string,string>>({}),[inicio,setInicio]=useState(''),[mensaje,setMensaje]=useState<string|null>(null)
  const cargar=async()=>{const [p,e]=await Promise.all([supabase.from('planteles').select('id,equipos(nombre),deportes(nombre),categorias(nombre)').order('id'),supabase.from('entrenamientos').select('id,plantel_id,inicio,estado').order('inicio',{ascending:false})]);if(!p.error)setPlanteles((p.data??[]).map((x:any)=>({id:x.id,nombre:[x.equipos?.nombre,x.deportes?.nombre,x.categorias?.nombre].filter(Boolean).join(' · ')})));if(!e.error)setEntrenamientos((e.data??[]) as Entrenamiento[])}
  useEffect(()=>{void cargar()},[])
  useEffect(()=>{if(!entrenamiento)return;void supabase.from('asistencias').select('inscripcion_id,estado').eq('entrenamiento_id',entrenamiento).then(({data})=>{const next:Record<string,string>={};(data??[]).forEach((x:any)=>{next[x.inscripcion_id]=x.estado});setEstados(next)});void supabase.from('inscripciones').select('id,jugador_id,camiseta,jugadores(nombre,apellido)').eq('plantel_id',plantel).eq('activa',true).then(({data})=>setInscripciones((data??[]) as Inscripcion[]))},[entrenamiento,plantel])
  const crear=async(e:FormEvent)=>{e.preventDefault();const {data,error}=await supabase.rpc('guardar_entrenamiento',{p_id:null as unknown as string,p_plantel_id:plantel,p_inicio:inicio,p_sede_id:null as unknown as string,p_estado:'realizado'});if(error)setMensaje('No se pudo crear el entrenamiento.');else{setMensaje('Entrenamiento creado.');setEntrenamiento(data);await cargar()}}
  const guardar=async(id:string,estado:string)=>{setEstados({...estados,[id]:estado});const {error}=await supabase.rpc('guardar_asistencia',{p_entrenamiento_id:entrenamiento,p_inscripcion_id:id,p_plantel_id:plantel,p_estado:estado});if(error)setMensaje('No se pudo guardar la asistencia.')}
  return <section className="panel"><h2>Entrenamientos y asistencia</h2><label>Plantel<select value={plantel} onChange={e=>{setPlantel(e.target.value);setEntrenamiento('')}}><option value="">Seleccionar</option>{planteles.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><form className="inline-form" onSubmit={e=>void crear(e)}><label>Inicio<input required type="datetime-local" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><button disabled={!plantel}>Crear sesión</button></form><label>Sesión<select value={entrenamiento} onChange={e=>setEntrenamiento(e.target.value)}><option value="">Seleccionar</option>{entrenamientos.filter(x=>x.plantel_id===plantel).map(x=><option key={x.id} value={x.id}>{new Date(x.inicio).toLocaleString()} · {x.estado}</option>)}</select></label>{entrenamiento&&<ul className="catalogo">{inscripciones.map(i=><li key={i.id}><span>{i.jugadores?.apellido}, {i.jugadores?.nombre}</span><select value={estados[i.id]??'sin_registrar'} onChange={e=>void guardar(i.id,e.target.value)}><option value="sin_registrar">Sin registrar</option><option value="presente">Presente</option><option value="ausente">Ausente</option></select></li>)}</ul>}{mensaje&&<p className="hint">{mensaje}</p>}</section>
}
