import { useEffect, useState } from 'react'
import { supabase } from '../../data/supabase'

type Partido = { id: string; inicio: string; local: { nombre: string } | null; visitante: { nombre: string } | null }
type Convocatoria = { id: string; inscripciones: { jugadores: { nombre: string; apellido: string } | null } | null; participaciones: { titular: boolean; capitan: boolean; presente: boolean | null; jugo: boolean | null; camiseta: number | null } | null }

export function CierrePartido() {
  const [partidos, setPartidos] = useState<Partido[]>([]), [partido, setPartido] = useState(''), [items, setItems] = useState<Convocatoria[]>([]), [resultado, setResultado] = useState({ local: '', visitante: '' }), [mensaje, setMensaje] = useState<string | null>(null)
  const cargar = async () => { const { data } = await supabase.from('partidos').select('id,inicio,local:equipos!partidos_local_id_fkey(nombre),visitante:equipos!partidos_visitante_id_fkey(nombre)').eq('estado', 'pendiente').order('inicio'); setPartidos((data ?? []) as Partido[]) }
  useEffect(() => { void cargar() }, [])
  const seleccionar = async (id: string) => { setPartido(id); const { data, error } = await supabase.from('convocatorias').select('id,inscripciones(jugadores(nombre,apellido)),participaciones(titular,capitan,presente,jugo,camiseta)').eq('partido_id', id).eq('convocado', true); if (error) setMensaje('No se pudo cargar la participación.'); else setItems((data ?? []) as Convocatoria[]) }
  const guardar = async (item: Convocatoria, cambios: Partial<NonNullable<Convocatoria['participaciones']>>) => { const actual = item.participaciones ?? { titular: false, capitan: false, presente: null, jugo: null, camiseta: null }; const p = { ...actual, ...cambios }; const { error } = await supabase.rpc('guardar_participacion', { p_convocatoria_id: item.id, p_titular: p.titular, p_capitan: p.capitan, p_presente: p.presente ?? false, p_jugo: p.jugo ?? false, p_camiseta: p.camiseta as unknown as number }); if (error) setMensaje('No se pudo guardar la participación.'); else { setItems(prev => prev.map(x => x.id === item.id ? { ...x, participaciones: p } : x)); setMensaje('Participación guardada.') } }
  const cerrar = async () => { const { error } = await supabase.rpc('guardar_resultado', { p_partido_id: partido, p_goles_local: Number(resultado.local), p_goles_visitante: Number(resultado.visitante) }); if (error) setMensaje(error.message.includes('No autorizado') ? 'No tenés permiso para cerrar este partido.' : 'No se pudo guardar el resultado.'); else { setMensaje('Partido cerrado y resultado guardado.'); setPartido(''); setItems([]); setResultado({ local: '', visitante: '' }); await cargar() } }
  return <section className="panel"><h2>Participación y cierre</h2><label>Partido<select value={partido} onChange={e => void seleccionar(e.target.value)}><option value="">Seleccionar</option>{partidos.map(p => <option key={p.id} value={p.id}>{new Date(p.inicio).toLocaleString()} · {p.local?.nombre} vs. {p.visitante?.nombre}</option>)}</select></label>{partido && <><ul className="catalogo">{items.map(i => { const p = i.participaciones ?? { titular: false, capitan: false, presente: false, jugo: false, camiseta: null }; return <li key={i.id}><span>{i.inscripciones?.jugadores?.apellido}, {i.inscripciones?.jugadores?.nombre}</span><span className="role-row"><label><input type="checkbox" checked={p.titular} onChange={e => void guardar(i, { titular: e.target.checked })} /> Titular</label><label><input type="checkbox" checked={p.capitan} onChange={e => void guardar(i, { capitan: e.target.checked })} /> Capitán</label><label><input type="checkbox" checked={!!p.presente} onChange={e => void guardar(i, { presente: e.target.checked })} /> Presente</label><label><input type="checkbox" checked={!!p.jugo} onChange={e => void guardar(i, { jugo: e.target.checked })} /> Jugó</label></span></li> })}</ul><div className="inline-form"><label>Goles local<input type="number" min="0" value={resultado.local} onChange={e => setResultado({ ...resultado, local: e.target.value })} /></label><label>Goles visitante<input type="number" min="0" value={resultado.visitante} onChange={e => setResultado({ ...resultado, visitante: e.target.value })} /></label><button disabled={resultado.local === '' || resultado.visitante === ''} onClick={() => void cerrar()}>Cerrar partido</button></div></>}{mensaje && <p className="hint">{mensaje}</p>}</section>
}
