import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../../data/supabase'

type Partido = { id: string; local_id: string; visitante_id: string; inicio: string; local: { nombre: string } | null; visitante: { nombre: string } | null }
type Convocatoria = { id: string; inscripciones: { jugadores: { nombre: string; apellido: string } | null } | null }

export function EventosPartido() {
  const [partidos, setPartidos] = useState<Partido[]>([]), [convocatorias, setConvocatorias] = useState<Convocatoria[]>([]), [partido, setPartido] = useState(''), [codigo, setCodigo] = useState('gol'), [nombre, setNombre] = useState('Gol'), [equipo, setEquipo] = useState(''), [jugador, setJugador] = useState(''), [minuto, setMinuto] = useState(''), [motivo, setMotivo] = useState(''), [sale, setSale] = useState(''), [entra, setEntra] = useState(''), [mensaje, setMensaje] = useState<string | null>(null)
  const cargar = async () => { const { data } = await supabase.from('partidos').select('id,local_id,visitante_id,inicio,local:equipos!partidos_local_id_fkey(nombre),visitante:equipos!partidos_visitante_id_fkey(nombre)').eq('estado', 'pendiente').order('inicio'); setPartidos((data ?? []) as Partido[]) }
  useEffect(() => { void cargar() }, [])
  const seleccionar = async (id: string) => { setPartido(id); const { data } = await supabase.from('convocatorias').select('id,inscripciones(jugadores(nombre,apellido))').eq('partido_id', id).eq('convocado', true); setConvocatorias((data ?? []) as Convocatoria[]); const p = partidos.find(x => x.id === id); setEquipo(p?.local_id ?? '') }
  const evento = async (e: FormEvent) => { e.preventDefault(); const { error } = await supabase.rpc('guardar_evento_partido', { p_partido_id: partido, p_codigo: codigo, p_nombre: nombre, p_convocatoria_id: jugador || null as unknown as string, p_asistidor_convocatoria_id: null as unknown as string, p_equipo_id: equipo, p_periodo: 1, p_minuto: minuto ? Number(minuto) : null as unknown as number, p_motivo: motivo }); setMensaje(error ? 'No se pudo guardar el evento.' : 'Evento guardado.'); if (!error) { setMinuto(''); setMotivo('') } }
  const cambio = async (e: FormEvent) => { e.preventDefault(); const { error } = await supabase.rpc('guardar_cambio', { p_partido_id: partido, p_sale_convocatoria_id: sale, p_entra_convocatoria_id: entra, p_periodo: 1, p_minuto: Number(minuto), p_motivo: motivo }); setMensaje(error ? `No se pudo guardar el cambio: ${error.message}` : 'Cambio guardado.'); if (!error) { setSale(''); setEntra(''); setMinuto(''); setMotivo('') } }
  return <section className="panel"><h2>Eventos y cambios</h2><label>Partido pendiente<select value={partido} onChange={e => void seleccionar(e.target.value)}><option value="">Seleccionar</option>{partidos.map(p => <option key={p.id} value={p.id}>{new Date(p.inicio).toLocaleString()} · {p.local?.nombre} vs. {p.visitante?.nombre}</option>)}</select></label>{partido && <><form className="inline-form" onSubmit={e => void evento(e)}><label>Código<input required value={codigo} onChange={e => setCodigo(e.target.value)} /></label><label>Nombre<input required value={nombre} onChange={e => setNombre(e.target.value)} /></label><label>Equipo<select required value={equipo} onChange={e => setEquipo(e.target.value)}><option value="">Seleccionar</option>{(() => { const p = partidos.find(x => x.id === partido); return <>{p?.local && <option value={p.local_id}>{p.local.nombre}</option>}{p?.visitante && <option value={p.visitante_id}>{p.visitante.nombre}</option>}</> })()}</select></label><label>Jugador<select value={jugador} onChange={e => setJugador(e.target.value)}><option value="">Sin jugador</option>{convocatorias.map(c => <option key={c.id} value={c.id}>{c.inscripciones?.jugadores?.apellido}, {c.inscripciones?.jugadores?.nombre}</option>)}</select></label><label>Minuto<input type="number" min="0" value={minuto} onChange={e => setMinuto(e.target.value)} /></label><label>Motivo<input value={motivo} onChange={e => setMotivo(e.target.value)} /></label><button>Guardar evento</button></form><form className="inline-form" onSubmit={e => void cambio(e)}><label>Sale<select required value={sale} onChange={e => setSale(e.target.value)}><option value="">Seleccionar</option>{convocatorias.map(c => <option key={c.id} value={c.id}>{c.inscripciones?.jugadores?.apellido}, {c.inscripciones?.jugadores?.nombre}</option>)}</select></label><label>Entra<select required value={entra} onChange={e => setEntra(e.target.value)}><option value="">Seleccionar</option>{convocatorias.filter(c => c.id !== sale).map(c => <option key={c.id} value={c.id}>{c.inscripciones?.jugadores?.apellido}, {c.inscripciones?.jugadores?.nombre}</option>)}</select></label><label>Minuto<input required type="number" min="0" value={minuto} onChange={e => setMinuto(e.target.value)} /></label><label>Motivo<input value={motivo} onChange={e => setMotivo(e.target.value)} /></label><button>Guardar cambio</button></form></>}{mensaje && <p className="hint">{mensaje}</p>}</section>
}
