import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../../data/supabase'

type Convocatoria = { id: string; convocado: boolean; respuesta: string; transporte: string | null; partidos: { inicio: string; cierre_confirmacion: string; estado: string; local: { nombre: string } | null; visitante: { nombre: string } | null; planteles: { deportes: { nombre: string } | null; categorias: { nombre: string } | null } | null } | null }

export function MisConvocatorias() {
  const [items, setItems] = useState<Convocatoria[]>([]), [respuestas, setRespuestas] = useState<Record<string, string>>({}), [transportes, setTransportes] = useState<Record<string, string>>({}), [mensaje, setMensaje] = useState<string | null>(null)
  const cargar = async () => { const { data, error } = await supabase.from('convocatorias').select('id,convocado,respuesta,transporte,partidos(inicio,cierre_confirmacion,estado,local:equipos!partidos_local_id_fkey(nombre),visitante:equipos!partidos_visitante_id_fkey(nombre),planteles(deportes(nombre),categorias(nombre)))').eq('convocado', true).order('id'); if (error) setMensaje('No se pudieron cargar tus convocatorias.'); else { const rows = (data ?? []) as Convocatoria[]; setItems(rows); setRespuestas(Object.fromEntries(rows.map(x => [x.id, x.respuesta]))); setTransportes(Object.fromEntries(rows.map(x => [x.id, x.transporte ?? '']))) } }
  useEffect(() => { void cargar() }, [])
  const responder = async (event: FormEvent, item: Convocatoria) => { event.preventDefault(); const respuesta = respuestas[item.id]; const { error } = await supabase.rpc('responder_convocatoria', { p_convocatoria: item.id, p_respuesta: respuesta, p_transporte: (transportes[item.id] || null) as unknown as string }); if (error) setMensaje(error.message.includes('cerrada') ? 'El plazo de respuesta ya cerró.' : 'No se pudo guardar la respuesta.'); else { setMensaje('Respuesta guardada.'); await cargar() } }
  return <section className="panel"><h2>Mis convocatorias</h2><p className="hint">Sólo aparecen convocatorias asociadas a tu ficha. Podés responder hasta el cierre indicado.</p>{items.length === 0 && <p className="hint">No tenés convocatorias pendientes.</p>}<ul className="catalogo">{items.map(item => { const p = item.partidos; if (!p) return null; const cerrado = new Date(p.cierre_confirmacion) <= new Date() || p.estado !== 'pendiente'; return <li key={item.id}><div><strong>{p.local?.nombre} vs. {p.visitante?.nombre}</strong><div className="hint">{p.planteles?.deportes?.nombre} · {p.planteles?.categorias?.nombre} · {new Date(p.inicio).toLocaleString()} · cierre {new Date(p.cierre_confirmacion).toLocaleString()}</div><form className="inline-form" onSubmit={e => void responder(e, item)}><label>Respuesta<select disabled={cerrado} value={respuestas[item.id] ?? 'pendiente'} onChange={e => setRespuestas(prev => ({ ...prev, [item.id]: e.target.value }))}><option value="pendiente">Pendiente</option><option value="acepta">Acepto</option><option value="rechaza">Rechazo</option></select></label><label>Transporte<input disabled={cerrado} value={transportes[item.id] ?? ''} onChange={e => setTransportes(prev => ({ ...prev, [item.id]: e.target.value }))} placeholder="Ej. voy por mi cuenta" /></label><button disabled={cerrado || respuestas[item.id] === 'pendiente'}>{cerrado ? 'Cierre vencido' : 'Guardar respuesta'}</button></form></div></li>})}</ul>{mensaje && <p className="hint">{mensaje}</p>}</section>
}
