import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../../data/supabase'

type Option = { id: string; nombre: string }
type Plantel = { id: string; equipos: { nombre: string } | null; deportes: { nombre: string } | null; categorias: { nombre: string } | null; temporadas: { nombre: string } | null }

export function PlantelesJugadores() {
  const [planteles, setPlanteles] = useState<Plantel[]>([]), [deportes, setDeportes] = useState<Option[]>([]), [categorias, setCategorias] = useState<Option[]>([]), [temporadas, setTemporadas] = useState<Option[]>([]), [equipos, setEquipos] = useState<Option[]>([])
  const [equipo, setEquipo] = useState(''), [deporte, setDeporte] = useState(''), [categoria, setCategoria] = useState(''), [temporada, setTemporada] = useState(''), [mensaje, setMensaje] = useState<string | null>(null)
  const cargar = async () => { const [p,d,c,t,e] = await Promise.all([supabase.from('planteles').select('id,equipos(nombre),deportes(nombre),categorias(nombre),temporadas(nombre)').order('id'),supabase.from('deportes').select('id,nombre').eq('activo',true).order('nombre'),supabase.from('categorias').select('id,nombre').eq('activo',true).order('orden'),supabase.from('temporadas').select('id,nombre').eq('activa',true).order('desde'),supabase.from('equipos').select('id,nombre').eq('activo',true).order('nombre')]); if(p.error) setMensaje('No se pudieron cargar los planteles.'); else setPlanteles((p.data ?? []) as Plantel[]); setDeportes((d.data ?? []) as Option[]); setCategorias((c.data ?? []) as Option[]); setTemporadas((t.data ?? []) as Option[]); setEquipos((e.data ?? []) as Option[]) }
  useEffect(() => { void cargar() }, [])
  const guardar = async (event: FormEvent) => { event.preventDefault(); const { error } = await supabase.rpc('guardar_plantel',{p_id:null as unknown as string,p_equipo_id:equipo,p_deporte_id:deporte,p_categoria_id:categoria,p_temporada_id:temporada,p_sede_id:null as unknown as string,p_activo:true}); if(error) setMensaje('No se pudo guardar el plantel.'); else { setMensaje('Plantel creado.'); await cargar() } }
  return <section className="panel"><h2>Planteles</h2><ul className="catalogo">{planteles.map(p=><li key={p.id}>{p.equipos?.nombre} · {p.deportes?.nombre} · {p.categorias?.nombre} · {p.temporadas?.nombre}</li>)}</ul><form className="inline-form" onSubmit={e=>void guardar(e)}>{[['Equipo',equipos,equipo,setEquipo],['Deporte',deportes,deporte,setDeporte],['Categoría',categorias,categoria,setCategoria],['Temporada',temporadas,temporada,setTemporada]].map(([label,options,value,setter])=><label key={label as string}>{label as string}<select required value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}><option value="">Seleccionar</option>{(options as Option[]).map(o=><option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label>)}<button>Crear plantel</button></form>{mensaje&&<p className="hint">{mensaje}</p>}</section>
}
